plugins:
  - jemoji
  - jekyll-paginate

title: "Brian Lee"
description: >
   Brian's DevBlog

email: brian.ts.lee.0907@gmail.com
logo: "/assets/images/black_memoji.png"
float_logo: true

cover: "/assets/images/blog_cover.jpeg"

name: 'Brian Lee'
author: 'Brian Lee'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://brian7989.github.io" # the base hostname & protocol for your site
baseurl: ""

#google_analytics: UA-XXXXX-X

social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/brian7989/
    desc: Connect on LinkedIn

  - icon:	facebook
    url:	https://www.facebook.com/brian.ts.lee.0907
    desc: Add me on Facebook

  - icon:	github
    url:	https://github.com/brian7989
    desc:	Follow me on GitHub
    share_url:
    share_title:
    share_link: